### ISSUE TITLE
"Error: channel closed" trace sometimes appears after "grunt test"

### ISSUE THREAD

**Issue by dborkan** [freedomjs/freedom-social-xmpp#92]
On the current master branch (i.e. without my latest ping changes), after running "grunt test" and seeing everything pass, I sometimes see this trace:
```
Error: channel closed
    at process.target.send (child_process.js:402:26)
    at context.postMessage (/Users/dborkan/github/freedom-social-xmpp-clean/node_modules/freedom-for-node/lib/modulecontext.js:43:13)
    at WorkerLink.deliverMessage (freedom.js.vm:4945:16)
    at Link.onMessage (freedom.js.vm:4797:10)
    at Hub.onMessage (freedom.js.vm:4604:30)
    at Object.<anonymous> (freedom.js.vm:7616:33)
    at Consumer.doEmit (freedom.js.vm:3917:10)
    at (anonymous function) [as write] (freedom.js.vm:6831:9)
    at FreedomTCP._writeNative (/Users/dborkan/github/freedom-social-xmpp-clean/spec/integration/../../dist/node-xmpp-browser.js:79:25)
    at null.<anonymous> (/Users/dborkan/github/freedom-social-xmpp-clean/spec/integration/../../dist/node-xmpp-browser.js:108:10)
```

**Comment by iislucas** [comment]
A freedom bug?

**Comment by willscott** [comment]
Looks like the xmpp-browser code was still trying to write out on the socket even as the module was being shut down.  We could have the test wait for `logout()` to finish before shutting down, or be less aggressive about trying to send out of modules.

This only affects shutdown time of freedom-for-node.
